### ISSUE TITLE
Is there a good reason the GitLab runner script does a lot of things with `sudo`?

### ISSUE THREAD

**Issue by pmj** [traderepublic/Cilicon#20]
I notice the GitLab [`start.command` runs a bunch of commands with `sudo`](https://github.com/traderepublic/Cilicon/blob/79b5755ca6e7b5ea161ce59eb24e020d4c2373ec/VM%20Resources/Gitlab%20Runner/start.command#L8). This doesn't seem strictly necessary, it could just install the runner binary in `~/bin` and run it from there, or something like that.

Is there a good reason why it's doing this with elevated privileges, or would you accept a patch that changes this behaviour so `sudo` is only needed for the `shutdown` at the end. (Which also has a bug in it… see #19 )

**Comment by pmj** [comment]
Thanks @Marcocanc for the heads-up. I look forward to the new update and won't bother with trying to get any changes merged into the current public version then. Happy to help with porting the GitLab runner to the new version if it doesn't involve too much Swift code, as that's not really my forte. (At least in 1.0 there doesn't seem to be any app side customisation needed, but if you're adding fancy stuff like picking VMs based on job tags in the new version then I guess it gets more complicated.)

**Comment by Marcocanc** [comment]
@pmj if you'd like to contribute the GitLab provisioner in 2.0 that would be amazing! Basically the main change is that we're dropping the Resources folder + Login Item approach in favor of SSH. Also it uses Tart's image format (but allows converting cilicon 1.0 images to the new format). If you're up for it, I will leave the code in for now. Otherwise I will remove it before merging to `main`.

**Comment by pmj** [comment]
I’m a bit snowed in work wise at the moment, so don’t wait around for me. However, I’ll almost certainly get around to making the GitLab runner work with it eventually if nobody else does so first.

**Comment by Marcocanc** [comment]
Hi @pmj , I added basic support for gitlab runners in the branch but currently it takes the registration token of a runner that was created via UI. Could you confirm that the original implementation creates this itself? Where did you take the token from for that? I found a runner registration token but it has a big deprecation warning on it.
