### ISSUE TITLE
Support for GitLab Runners

### ISSUE THREAD

**Issue by Marcocanc** [traderepublic/Cilicon#23]
Unfortunately we due to the major changes in Cilicon 2.0 we had to break/remove support for GitLab runners.
Hoping that someone who uses GitLab could contribute the provisioner.
@ast3150 perhaps you could have a look?

**Comment by ast3150** [comment]
2.0 looks nice! Yeah I can take a look when I get the chance ✨

**Comment by Marcocanc** [comment]
I started a gitlab trial and tried to implement it myself, but I got a bit confused as registration tokens were deprecated. I find their documentation really confusing (authentication token vs. registration token).

**Comment by ast3150** [comment]
I've conducted some more investigation into the upcoming changes for GitLab Runner registration. GitLab plan to remove the runner registration token in GitLab 16.6, which will be available in about 4 months. 

So, for the Cilicon v2.0 compatibility upgrade of the GitLab Provisioner, I'll try to migrate to the new runner registration workflow to ensure future support.

This means that GitLab will only be supported from 16.0+ with the new GitLab Provisioner implementation.

**Comment by PaulWoitaschek** [comment]
Thanks for your efforts and investigations! We're very much looking forward to it.

**Comment by ast3150** [comment]
Loving the new Shell-based approach. In combination with the token changes, the complexity has been reduced by a lot 🎉 

Changes are ready for review @Marcocanc
