### ISSUE TITLE
Migrating from v1.1.0 to v2.0 does lead to NIOConnectionError

### ISSUE THREAD

**Issue by rubenvde** [traderepublic/Cilicon#25]
I'm trying to convert from v1.1.0 to v2.0 but I wasn't able to because the vm wouldn't start. I changed the yml file `vmBundlePath` to `source`, it tries to convert the VM to the new standard so I clicked yes, but then it is not able to connect and I get this error all the time:

<img width="624" alt="Screenshot 2023-06-19 at 14 14 12" src="https://github.com/traderepublic/Cilicon/assets/2741870/ddeed293-1fdb-45dc-a702-4862e3b9f69f">

I'm running this on a M2 Pro Mac mini. Ventura 13.2.1.

**Comment by Marcocanc** [comment]
@rubenvde Have you enabled SSH on the VM and either set the default credentials (`admin`:`admin`) or configured your own in the config file? If not you will have to enter `editorMode` first to make these changes.
Sorry, the documentation is not particularly clear on this. I will amend this info soon.

@Joannis I thought I was printing the `localizedDescription`. Will have a look at what's going on.

**Comment by rubenvde** [comment]
@Marcocanc It looks like that resolves the issue. Yeah I had no idea that I had to do that. Please add it in some form of documentation. But thanks for the quick response!
