### ISSUE TITLE
Use dotfile for cilicon.yml config

### ISSUE THREAD

**Issue by torarnv** [traderepublic/Cilicon#29]
Placing a cilicon.yml in the home directory is unconventional for macOS. A more common approach is `.cilicon.yml`. Or use NSUserDefaults, which reads from ~/Library/Preferences

**Comment by Marcocanc** [comment]
Thanks for raising the issue. In our first prototype the yml file was acutally a (hidden) dotfile. I found that having it in an easily accessible location (the users' home) and not hidden made provisioning and maintenance a lot easier. I believe that convenience wins over conventionalism here, but am open for any other arguments.

**Comment by Joannis** [comment]
I concur with having a hidden file. At least giving it a fallback option to either one or the other is a good solution.

**Comment by ast3150** [comment]
How about making the path customizable? The app could prompt the user for a path if the config file is not found in the default location. This could be added to the fallback view where currently the default config can be created.

**Comment by Marcocanc** [comment]
I would prefer not to add unnecessary complexity (UI etc.) for this. Let's have Cilicon look for either `cilicon.yml` or `.cilicon.yml` if it can't find the former.
