### ISSUE TITLE
Couldn't resolve host | Message queue listen OAuth token

### ISSUE THREAD

**Issue by AllDmeat** [traderepublic/Cilicon#35]
> macOS 13.2.1
> Cilicon 1.1.0

5 of 6 machines from our CI stopped working without any changes being made by our team today.
<img width="365" alt="Screenshot 2023-08-22 at 13 04 22" src="https://github.com/traderepublic/Cilicon/assets/5537636/48e7c04f-fa0b-44cd-bcda-13f8dcd84ee3">

I've switched machines to editor mode and had enough time to compare network configs of working and non-working machines. There are differences.

Working config:
<img width="295" alt="Screenshot 2023-08-22 at 14 52 19" src="https://github.com/traderepublic/Cilicon/assets/5537636/7e1956be-bf73-43f4-a252-9c0914c255a5">

Non-working config:
<img width="293" alt="Screenshot 2023-08-22 at 14 53 10" src="https://github.com/traderepublic/Cilicon/assets/5537636/642254b4-2843-4586-9eb1-a0bf026e1a2b">

All non-working configs have empty `Router`, `255.255.0.0``Mask` and IPs starting from `169`

What's interesting is that if I wait for a few minutes the VM will finally get valid network settings.

I've tried switching from DHCP to manual config and that helps with network problem, but I immediately do face another issue — something related to token:
<img width="353" alt="Screenshot 2023-08-22 at 13 27 30" src="https://github.com/traderepublic/Cilicon/assets/5537636/fe2fbbd6-07da-4d20-8fdc-edbd2335906f">
I've found this exact exception in [runner sources](https://github.com/actions/runner/blob/73ef82ff859511665c28a26331818311fb2439b2/src/Runner.Listener/Configuration/ConfigurationManager.cs#L363), but I couldn't figure out what's wrong and how to fix it. 

I believe that token is valid, because one of CI machines is still working fine, using exact same token.
Anyway I've generated and provided new token with no luck.

I know that I'm using an outdated version of macOS and Cilicon — I've just had no time to install the update.

So at the end I have this questions:
1. What could have happened to network settings?
2. What is the problem with token?
3. What can I do to fix issues?

**Comment by AllDmeat** [comment]
I've tried updating Cilicon, but that didn't help.
After Cilicon launch app title doesn't contain IP address (as it does in [your examples](
![](https://user-images.githubusercontent.com/1622982/244096303-31a0e031-4938-4d42-bc75-6ee29269abe4.gif)
)) and SSH session cannot start (if empty bottom half of the screen means that).
<img width="1325" alt="Screenshot 2023-08-23 at 12 29 29" src="https://github.com/traderepublic/Cilicon/assets/5537636/6e0a6031-538e-4e69-8208-b5a150e7005a">

I have Remote Login enabled and tried both default credentials and manual creds specification using `cilicon.yml`, but still no luck.

**Comment by AllDmeat** [comment]
Managed to solve "Message queue listen OAuth token" exception.
This has to do with shutting down the VM while the job is in progress, causing the runner on GitHub to remain in some sort of hanging state.

Still don't know why the network using DHCP resolves invalid config and SSH can't connect to the VM. Any suggestions?

**Comment by Marcocanc** [comment]
Hi @AllDmeat, sorry I only saw this issue now. Will look into it this week and report back.

**Comment by Marcocanc** [comment]
Firstly, I would exclude the Oauth token exception from the scope of this issue, as it seems to be related to the runner not being removed correctly.

Interestingly we had a similar issue where on Wednesday where several of our machines no got stuck (Cilicon couldn't connect via SSH after VM reboot), all in the same timeframe. I'm still investigating what could be the cause and why the issue affected several of them at the same time, which indicates that there may be some external factor at play.

**Comment by AllDmeat** [comment]
Issue with the token is resolved. Here's discussion: https://github.com/orgs/community/discussions/64812
Network issue still persists.
