### ISSUE TITLE
Sonoma images not working

### ISSUE THREAD

**Issue by avalanched** [traderepublic/Cilicon#44]
I was trying the sonoma xcode 15.01. image ( https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-sonoma-xcode/144771897?tag=15.0.1) but it seems they have `application/vnd.cirruslabs.tart.disk.v2` for the image in their name and the VMManager is specifically filtering for `application/vnd.cirruslabs.tart.disk.v1`.

Im not sure why this is the case.

**Comment by Marcocanc** [comment]
Sorry for the delay on this. It's currently being worked on and should be ready by early January.

**Comment by Marcocanc** [comment]
Check 2.2.0. Sorry it took so long!
