### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by marcusramberg** [traderepublic/Cilicon#45]
Hey.

I have a problem with Cilicon crashing on startup. It's probably related to a misconfiguration on my ec2-builder, but the crash makes it hard to tell what goes on.

I've attached it to this ticket, any idea where it's stopping? I've had a very similar config run fine on a local mac. This is with v2.1.0 from github releases.

[crash.txt](https://github.com/traderepublic/Cilicon/files/13902105/crash.txt)

*edit* I've built and uploaded cilicon to get symbols, and this is a bit more useful:

[crash-sym.txt](https://github.com/traderepublic/Cilicon/files/13902538/crash-sym.txt)

Looks like it's crashing in the lease parser because /var/db/dhcpd_leases can't be found. On my builder I see 

```
sudo ls /var/db/dhcpclient/leases
en4.plist       en7.plist
```
but not the /var/db/dhcpd_leases file.

**Comment by marcusramberg** [comment]
Seems like if you touch this file, it will start getting leases and the vm will start up.

**Comment by Marcocanc** [comment]
I will add a check to see if the file exists. Thanks for reporting.
Does the provisioner work after starting the VM?

**Comment by marcusramberg** [comment]
Yeah, although it seems there's some timing issue where ssh connection happens before ssh is available sometimes, leading to a new cycle. I've been experimenting with adding a configurable delay before ssh connect in a fork, could open a PR for that if it's interesting.

**Comment by Marcocanc** [comment]
I'm gonna release a new version today that should fix issues related to the lease. It will simply create a new VM as long as it fails to get a valid ip

**Comment by nikolaik** [comment]
> I'm gonna release a new version today that should fix issues related to the lease. It will simply create a new VM as long as it fails to get a valid ip

Hitting this too, is there a branch I can test with your changes?

**Comment by Marcocanc** [comment]
The current `main` branch already has a fix for the lease parser included, it's just not available in the github release.

**Comment by Marcocanc** [comment]
The latest release should have fixed this. Closing for now, feel free to re-open if the problem persists.
