### ISSUE TITLE
improve error message that doesn't help at all; dataCorrupted

### ISSUE THREAD

**Issue by jupe** [traderepublic/Cilicon#48]
I except that my cilicon.yml config was invalid somehow, but failure message doesn't help at all to identify issue; 
<img width="820" alt="Screenshot 2024-01-21 at 20 22 02" src="https://github.com/traderepublic/Cilicon/assets/3822425/77fadc66-7b5b-4093-8ec0-f605d7741166">

Propose to give at least filename or even line number which is invalid. This would help for learning curve.

**Comment by Marcocanc** [comment]
Hi @jupe , we're just showing the native description of the respective error. This error indicates a problem in the VM source path. If you've tried troubleshooting but can't get it to work, I can have a look if you post your yml file here.

**Comment by jupe** [comment]
I know, unfortunately that's not human friendly at all which was the reason I raised this ticket.

**Comment by Marcocanc** [comment]
Yes it would be possible, but compared to other features/changes it's currently very low priority. However we're very open to external contributions 😊
