### ISSUE TITLE
Unclear failure with GitHub token

### ISSUE THREAD

**Issue by ewdurbin** [traderepublic/Cilicon#51]
On launch, the VM loops:

![Screenshot 2024-05-08 at 12 31 48 PM](https://github.com/traderepublic/Cilicon/assets/1200832/d95991d0-20d4-449d-8650-d882779d0723)

I don't see any other log or obvious issue.

**Comment by Marcocanc** [comment]
@ewdurbin Verison 2.2.1 should now display detailed information about any errors encountered during provisioning. Please give it a try and feel free to reopen the issue in case you can't solve with or it's an actual Cilicon bug.
